version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      APP_PGSQL_CONNECTION_STRING: "postgresql://user:password@postgres/db"
    depends_on:
      postgres:
        condition: service_healthy
    links: 
        - postgres
  postgres:
    image: postgres:16.3-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db -u user"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s  
