version: "3.8"


services:
  #web:
    #build: .
    #ports:
      #- "8000:5000"
  postgres:
    image: postgres:16.3-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
